ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "rosterDayShiftGuardsRequired" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "rosterNightShiftGuardsRequired" INTEGER NOT NULL DEFAULT 1;
