import { jsPDF } from "jspdf";
import { addDays, format, parseISO } from "date-fns";

export interface RosterShift {
  id: string;
  startTime: string;
  endTime: string;
  status: string;
  employee: { id: string; firstName: string; lastName: string };
  post: { id: string; name: string; shiftType: string | null; site: { name: string } };
}

const WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] as const;

function getGeneratedByText(generatedBy?: string): string {
  const dateStr = format(new Date(), "d MMM yyyy HH:mm");
  return generatedBy ? `Generated by ${generatedBy} on ${dateStr}` : `Generated ${dateStr}`;
}

/** Build display cells with Mon–Sun alignment (padding for calendar grid). */
function buildDisplayCells(calendarDays: Date[]): (Date | null)[] {
  if (calendarDays.length === 0) return [];
  const firstDay = calendarDays[0]!.getDay();
  const startPad = (firstDay - 1 + 7) % 7;
  const endPad = (7 - ((startPad + calendarDays.length) % 7)) % 7;
  return [
    ...Array(startPad).fill(null),
    ...calendarDays,
    ...Array(endPad).fill(null),
  ];
}

/** Map yyyy-MM-dd to shifts for that day. */
function getShiftsByDay(
  shifts: RosterShift[],
  calendarDays: Date[]
): Map<string, RosterShift[]> {
  const map = new Map<string, RosterShift[]>();
  for (const day of calendarDays) {
    map.set(format(day, "yyyy-MM-dd"), []);
  }
  for (const shift of shifts) {
    const key = format(parseISO(shift.startTime), "yyyy-MM-dd");
    if (map.has(key)) {
      map.get(key)!.push(shift);
    }
  }
  for (const arr of map.values()) {
    arr.sort((a, b) => parseISO(a.startTime).getTime() - parseISO(b.startTime).getTime());
  }
  return map;
}

/** Abbreviate name to "J. Smith" style. */
function abbreviateName(firstName: string, lastName: string): string {
  const initial = firstName.charAt(0).toUpperCase();
  return `${initial}. ${lastName}`;
}

type ShiftFormatter = (s: RosterShift) => string[];

/** Draw a calendar grid on the PDF. */
function drawCalendarGrid(
  doc: jsPDF,
  displayCells: (Date | null)[],
  shiftsByDay: Map<string, RosterShift[]>,
  formatShift: ShiftFormatter,
  options: {
    marginLeft: number;
    marginTop: number;
    pageWidth: number;
    pageHeight: number;
    bottomMargin: number;
  }
): void {
  const { marginLeft, marginTop, pageWidth, pageHeight, bottomMargin } = options;
  const gridWidth = pageWidth - marginLeft * 2;
  const cellWidth = gridWidth / 7;
  const headerHeight = 10;
  const dateRowHeight = 12;
  const cellPadding = 4;
  const shiftFontSize = 7;
  const lineHeight = 4;

  let y = marginTop;

  // Weekday headers
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  for (let col = 0; col < 7; col++) {
    const x = marginLeft + col * cellWidth;
    doc.rect(x, y, cellWidth, headerHeight);
    doc.text(WEEKDAYS[col], x + cellWidth / 2, y + headerHeight / 2 + 1.5, {
      align: "center",
    });
  }
  y += headerHeight;

  // Compute max content height per row (for equal-height cells)
  const rows: (Date | null)[][] = [];
  for (let i = 0; i < displayCells.length; i += 7) {
    rows.push(displayCells.slice(i, i + 7));
  }

  const minCellContentHeight = 24;

  for (const row of rows) {
    let maxLines = 0;
    for (const day of row) {
      if (!day) continue;
      const key = format(day, "yyyy-MM-dd");
      const dayShifts = shiftsByDay.get(key) ?? [];
      const lines: string[] = [];
      for (const s of dayShifts) {
        lines.push(...formatShift(s));
      }
      maxLines = Math.max(maxLines, lines.length);
    }
    const contentHeight = Math.max(
      minCellContentHeight,
      maxLines * lineHeight + cellPadding * 2
    );
    const cellHeight = dateRowHeight + contentHeight;

    // Check if we need a new page
    if (y + cellHeight > pageHeight - bottomMargin) {
      doc.addPage();
      y = marginTop;
      // Redraw weekday headers on new page
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      for (let col = 0; col < 7; col++) {
        const x = marginLeft + col * cellWidth;
        doc.rect(x, y, cellWidth, headerHeight);
        doc.text(WEEKDAYS[col], x + cellWidth / 2, y + headerHeight / 2 + 1.5, {
          align: "center",
        });
      }
      y += headerHeight;
    }

    // Date row
    for (let col = 0; col < 7; col++) {
      const x = marginLeft + col * cellWidth;
      doc.rect(x, y, cellWidth, cellHeight);
      const day = row[col];
      if (day) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text(format(day, "d"), x + cellWidth / 2, y + 6, { align: "center" });
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text(format(day, "MMM"), x + cellWidth / 2, y + 11, {
          align: "center",
        });
        doc.setTextColor(0, 0, 0);

        const key = format(day, "yyyy-MM-dd");
        const dayShifts = shiftsByDay.get(key) ?? [];
        doc.setFontSize(shiftFontSize);
        let lineY = y + dateRowHeight + cellPadding;
        const maxTextWidth = cellWidth - cellPadding * 2;
        for (const s of dayShifts) {
          for (const part of formatShift(s)) {
            const wrapped = doc.splitTextToSize(part, maxTextWidth);
            for (const w of wrapped) {
              if (lineY > y + cellHeight - cellPadding) break;
              doc.text(w, x + cellPadding, lineY);
              lineY += lineHeight;
            }
          }
        }
      }
    }
    y += cellHeight;
  }
}

/**
 * Generate a PDF blob for the full workforce roster.
 * Uses a calendar grid layout: Mon–Sun columns, each cell shows shifts for that day.
 */
export function generateFullRosterPDF(
  shifts: RosterShift[],
  calendarDays: Date[],
  periodLabel: string,
  generatedBy?: string
): Blob {
  const useLandscape = calendarDays.length > 14;
  const doc = new jsPDF({ orientation: useLandscape ? "landscape" : "portrait" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 14;
  const marginTop = 35;
  const bottomMargin = 20;

  doc.setFontSize(12);
  doc.text("Roster", marginLeft, 16);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(periodLabel, marginLeft, 22);
  doc.text(getGeneratedByText(generatedBy), marginLeft, 27);
  doc.setTextColor(0, 0, 0);

  if (shifts.length === 0) {
    doc.setFontSize(10);
    doc.text("No shifts scheduled for this period.", marginLeft, 40);
  } else {
    const displayCells = buildDisplayCells(calendarDays);
    const shiftsByDay = getShiftsByDay(shifts, calendarDays);
    const formatShift: ShiftFormatter = (s) => {
      const start = parseISO(s.startTime);
      const end = parseISO(s.endTime);
      const type = (s.post.shiftType ?? "day").charAt(0).toUpperCase();
      const name = abbreviateName(s.employee.firstName, s.employee.lastName);
      return [
        `${name}`,
        `${s.post.name} ${type}`,
        `${format(start, "HH:mm")}-${format(end, "HH:mm")}`,
      ];
    };
    drawCalendarGrid(doc, displayCells, shiftsByDay, formatShift, {
      marginLeft,
      marginTop,
      pageWidth,
      pageHeight,
      bottomMargin,
    });
  }

  return doc.output("blob");
}

/**
 * Generate a PDF blob for a single guard's roster.
 * Uses a calendar grid layout: Mon–Sun columns, each cell shows that guard's shifts for that day.
 */
export function generateGuardRosterPDF(
  shifts: RosterShift[],
  employeeName: string,
  periodLabel: string,
  generatedBy?: string
): Blob {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 14;
  const marginTop = 35;
  const bottomMargin = 20;

  doc.setFontSize(12);
  doc.text(`${employeeName} – Roster`, marginLeft, 16);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(periodLabel, marginLeft, 22);
  doc.text(getGeneratedByText(generatedBy), marginLeft, 27);
  doc.setTextColor(0, 0, 0);

  const sortedShifts = [...shifts].sort(
    (a, b) => parseISO(a.startTime).getTime() - parseISO(b.startTime).getTime()
  );

  if (sortedShifts.length === 0) {
    doc.setFontSize(10);
    doc.text("No shifts scheduled for this period.", marginLeft, 40);
  } else {
    const calendarDays: Date[] = [];
    const seen = new Set<string>();
    for (const s of sortedShifts) {
      const key = format(parseISO(s.startTime), "yyyy-MM-dd");
      if (!seen.has(key)) {
        seen.add(key);
        calendarDays.push(parseISO(s.startTime));
      }
    }
    calendarDays.sort((a, b) => a.getTime() - b.getTime());

    // Build full date range from min to max
    const minDate = calendarDays[0]!;
    const maxDate = calendarDays[calendarDays.length - 1]!;
    const fullCalendarDays: Date[] = [];
    let d = new Date(minDate);
    while (d <= maxDate) {
      fullCalendarDays.push(new Date(d));
      d = addDays(d, 1);
    }

    const displayCells = buildDisplayCells(fullCalendarDays);
    const shiftsByDay = getShiftsByDay(sortedShifts, fullCalendarDays);
    const formatShift: ShiftFormatter = (s) => {
      const start = parseISO(s.startTime);
      const end = parseISO(s.endTime);
      const type = (s.post.shiftType ?? "day").charAt(0).toUpperCase();
      return [
        `${s.post.site.name} – ${s.post.name}`,
        `${type} ${format(start, "HH:mm")}-${format(end, "HH:mm")}`,
      ];
    };
    drawCalendarGrid(doc, displayCells, shiftsByDay, formatShift, {
      marginLeft,
      marginTop,
      pageWidth,
      pageHeight,
      bottomMargin,
    });
  }

  return doc.output("blob");
}
