import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { format, parseISO } from "date-fns";

export interface RosterShift {
  id: string;
  startTime: string;
  endTime: string;
  status: string;
  employee: { id: string; firstName: string; lastName: string };
  post: { id: string; name: string; shiftType: string | null; site: { name: string } };
}

const WIREFRAME_STYLES = {
  lineWidth: 0.1,
  lineColor: [0, 0, 0] as [number, number, number],
  fillColor: [255, 255, 255] as [number, number, number],
  textColor: [0, 0, 0] as [number, number, number],
};

const HEADER_STYLES = {
  fillColor: [250, 250, 250] as [number, number, number],
  textColor: [0, 0, 0] as [number, number, number],
  fontStyle: "bold" as const,
};

function getGeneratedByText(generatedBy?: string): string {
  const dateStr = format(new Date(), "d MMM yyyy HH:mm");
  return generatedBy ? `Generated by ${generatedBy} on ${dateStr}` : `Generated ${dateStr}`;
}

/**
 * Generate a PDF blob for the full workforce roster.
 * Uses a site-grouped layout: each site as section header with Date | Employee | Post | Type | Start | End table.
 */
export function generateFullRosterPDF(
  shifts: RosterShift[],
  calendarDays: Date[],
  periodLabel: string,
  generatedBy?: string
): Blob {
  const useLandscape = calendarDays.length > 14;
  const doc = new jsPDF({ orientation: useLandscape ? "landscape" : "portrait" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottomMargin = 20;

  doc.setFontSize(12);
  doc.text("Roster", 14, 16);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(periodLabel, 14, 22);
  doc.text(getGeneratedByText(generatedBy), 14, 27);
  doc.setTextColor(0, 0, 0);

  if (shifts.length === 0) {
    doc.setFontSize(10);
    doc.text("No shifts scheduled for this period.", 14, 40);
  } else {
    // Group shifts by site (alphabetically)
    const bySite = new Map<string, RosterShift[]>();
    for (const s of shifts) {
      const siteName = s.post.site.name;
      if (!bySite.has(siteName)) bySite.set(siteName, []);
      bySite.get(siteName)!.push(s);
    }
    const siteNames = [...bySite.keys()].sort();

    let startY = 35;
    const head = [["Date", "Employee", "Post", "Type", "Start", "End"]];

    for (const siteName of siteNames) {
      const siteShifts = bySite.get(siteName)!.sort(
        (a, b) => parseISO(a.startTime).getTime() - parseISO(b.startTime).getTime()
      );
      const body = siteShifts.map((s) => {
        const start = parseISO(s.startTime);
        return [
          format(start, "EEE d MMM"),
          `${s.employee.firstName} ${s.employee.lastName}`,
          s.post.name,
          s.post.shiftType ?? "day",
          format(start, "HH:mm"),
          format(parseISO(s.endTime), "HH:mm"),
        ];
      });

      // New page if site section wouldn't fit (roughly: header + table needs ~50px min)
      if (startY > pageHeight - bottomMargin - 50) {
        doc.addPage(doc.internal.pageSize.getWidth() > doc.internal.pageSize.getHeight() ? "landscape" : "portrait");
        startY = 20;
      }

      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text(siteName, 14, startY);
      doc.setFont("helvetica", "normal");
      startY += 8;

      autoTable(doc, {
        head,
        body,
        startY,
        styles: {
          fontSize: 9,
          cellPadding: 3,
          ...WIREFRAME_STYLES,
        },
        headStyles: {
          ...HEADER_STYLES,
          ...WIREFRAME_STYLES,
        },
        alternateRowStyles: {
          fillColor: [252, 252, 252] as [number, number, number],
        },
        margin: { left: 14 },
        tableWidth: pageWidth - 28,
      });

      startY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
    }
  }

  return doc.output("blob");
}

/**
 * Generate a PDF blob for a single guard's roster.
 * Table: Date | Site | Post | Type | Start | End
 */
export function generateGuardRosterPDF(
  shifts: RosterShift[],
  employeeName: string,
  periodLabel: string,
  generatedBy?: string
): Blob {
  const doc = new jsPDF();

  doc.setFontSize(12);
  doc.text(`${employeeName} – Roster`, 14, 16);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(periodLabel, 14, 22);
  doc.text(getGeneratedByText(generatedBy), 14, 27);
  doc.setTextColor(0, 0, 0);

  const filteredShifts = shifts.sort(
    (a, b) => parseISO(a.startTime).getTime() - parseISO(b.startTime).getTime()
  );

  if (filteredShifts.length === 0) {
    doc.setFontSize(10);
    doc.text("No shifts scheduled for this period.", 14, 40);
  } else {
    // #region agent log
    const sample = filteredShifts[0];
    if (sample) {
      const startParsed = parseISO(sample.startTime);
      const endParsed = parseISO(sample.endTime);
      fetch('http://127.0.0.1:7244/ingest/f56a901b-0402-4f99-950f-9d91bcf073da',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location:'roster-pdf.ts:generateGuardRosterPDF',message:'Guard PDF time formatting',data:{rawStartTime:sample.startTime,rawEndTime:sample.endTime,startFormatted:format(startParsed,'HH:mm'),endFormatted:format(endParsed,'HH:mm'),tzOffsetMin:new Date().getTimezoneOffset()},hypothesisId:'H1,H2,H3,H4,H5',timestamp:Date.now()})}).catch(()=>{});
    }
    // #endregion
    const head = [["Date", "Site", "Post", "Type", "Start", "End"]];
    const body = filteredShifts.map((s) => {
      const start = parseISO(s.startTime);
      return [
        format(start, "EEE d MMM"),
        s.post.site.name,
        s.post.name,
        s.post.shiftType ?? "day",
        format(start, "HH:mm"),
        format(parseISO(s.endTime), "HH:mm"),
      ];
    });

    autoTable(doc, {
      head,
      body,
      startY: 32,
      styles: {
        fontSize: 10,
        cellPadding: 3,
        ...WIREFRAME_STYLES,
      },
      headStyles: {
        ...HEADER_STYLES,
        ...WIREFRAME_STYLES,
      },
      alternateRowStyles: {
        fillColor: [252, 252, 252] as [number, number, number],
      },
      margin: { left: 14 },
    });
  }

  return doc.output("blob");
}
