import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { format, parseISO } from "date-fns";
import type { ShiftSheetRow } from "./shift-sheet-matrix";
import { genderPdfLabel } from "./shift-sheet-matrix";
import { formatPhoneForDisplay } from "./phone-format";
import { rosterSiteRulesLines } from "./roster-site-rules-defaults";

export interface RosterShift {
  id: string;
  startTime: string;
  endTime: string;
  status: string;
  employee: { id: string; firstName: string; lastName: string };
  post: { id: string; name: string; shiftType: string | null; site: { name: string } };
}

const WIREFRAME_STYLES = {
  lineWidth: 0.1,
  lineColor: [0, 0, 0] as [number, number, number],
  fillColor: [255, 255, 255] as [number, number, number],
  textColor: [0, 0, 0] as [number, number, number],
};

const HEADER_STYLES = {
  fillColor: [250, 250, 250] as [number, number, number],
  textColor: [0, 0, 0] as [number, number, number],
  fontStyle: "bold" as const,
};

function getGeneratedByText(generatedBy?: string): string {
  const dateStr = format(new Date(), "d MMM yyyy HH:mm");
  return generatedBy ? `Generated by ${generatedBy} on ${dateStr}` : `Generated ${dateStr}`;
}

/**
 * Generate a PDF blob for the full workforce roster.
 * Uses a site-grouped layout: each site as section header with Date | Employee | Post | Type | Start | End table.
 */
export function generateFullRosterPDF(
  shifts: RosterShift[],
  calendarDays: Date[],
  periodLabel: string,
  generatedBy?: string
): Blob {
  const useLandscape = calendarDays.length > 14;
  const doc = new jsPDF({ orientation: useLandscape ? "landscape" : "portrait" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottomMargin = 20;

  doc.setFontSize(12);
  doc.text("Roster", 14, 16);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(periodLabel, 14, 22);
  doc.text(getGeneratedByText(generatedBy), 14, 27);
  doc.setTextColor(0, 0, 0);

  if (shifts.length === 0) {
    doc.setFontSize(10);
    doc.text("No shifts scheduled for this period.", 14, 40);
  } else {
    // Group shifts by site (alphabetically)
    const bySite = new Map<string, RosterShift[]>();
    for (const s of shifts) {
      const siteName = s.post.site.name;
      if (!bySite.has(siteName)) bySite.set(siteName, []);
      bySite.get(siteName)!.push(s);
    }
    const siteNames = [...bySite.keys()].sort();

    let startY = 35;
    const head = [["Date", "Employee", "Post", "Type", "Start", "End"]];

    for (const siteName of siteNames) {
      const siteShifts = bySite.get(siteName)!.sort(
        (a, b) => parseISO(a.startTime).getTime() - parseISO(b.startTime).getTime()
      );
      const body = siteShifts.map((s) => {
        const start = parseISO(s.startTime);
        return [
          format(start, "EEE d MMM"),
          `${s.employee.firstName} ${s.employee.lastName}`,
          s.post.name,
          s.post.shiftType ?? "day",
          format(start, "HH:mm"),
          format(parseISO(s.endTime), "HH:mm"),
        ];
      });

      // New page if site section wouldn't fit (roughly: header + table needs ~50px min)
      if (startY > pageHeight - bottomMargin - 50) {
        doc.addPage(doc.internal.pageSize.getWidth() > doc.internal.pageSize.getHeight() ? "landscape" : "portrait");
        startY = 20;
      }

      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text(siteName, 14, startY);
      doc.setFont("helvetica", "normal");
      startY += 8;

      autoTable(doc, {
        head,
        body,
        startY,
        styles: {
          fontSize: 9,
          cellPadding: 3,
          ...WIREFRAME_STYLES,
        },
        headStyles: {
          ...HEADER_STYLES,
          ...WIREFRAME_STYLES,
        },
        alternateRowStyles: {
          fillColor: [252, 252, 252] as [number, number, number],
        },
        margin: { left: 14 },
        tableWidth: pageWidth - 28,
      });

      startY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
    }
  }

  return doc.output("blob");
}

/**
 * Generate a PDF blob for a single guard's roster.
 * Table: Date | Site | Post | Type | Start | End
 */
export function generateGuardRosterPDF(
  shifts: RosterShift[],
  employeeName: string,
  periodLabel: string,
  generatedBy?: string
): Blob {
  const doc = new jsPDF();

  doc.setFontSize(12);
  doc.text(`${employeeName} – Roster`, 14, 16);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(periodLabel, 14, 22);
  doc.text(getGeneratedByText(generatedBy), 14, 27);
  doc.setTextColor(0, 0, 0);

  const filteredShifts = shifts.sort(
    (a, b) => parseISO(a.startTime).getTime() - parseISO(b.startTime).getTime()
  );

  if (filteredShifts.length === 0) {
    doc.setFontSize(10);
    doc.text("No shifts scheduled for this period.", 14, 40);
  } else {
    const head = [["Date", "Site", "Post", "Type", "Start", "End"]];
    const body = filteredShifts.map((s) => {
      const start = parseISO(s.startTime);
      return [
        format(start, "EEE d MMM"),
        s.post.site.name,
        s.post.name,
        s.post.shiftType ?? "day",
        format(start, "HH:mm"),
        format(parseISO(s.endTime), "HH:mm"),
      ];
    });

    autoTable(doc, {
      head,
      body,
      startY: 32,
      styles: {
        fontSize: 10,
        cellPadding: 3,
        ...WIREFRAME_STYLES,
      },
      headStyles: {
        ...HEADER_STYLES,
        ...WIREFRAME_STYLES,
      },
      alternateRowStyles: {
        fillColor: [252, 252, 252] as [number, number, number],
      },
      margin: { left: 14 },
    });
  }

  return doc.output("blob");
}

export interface ShiftRosterSheetPdfInput {
  siteName: string;
  periodLabel: string;
  days: Date[];
  rows: ShiftSheetRow[];
  generatedBy?: string;
  rosterSiteRules?: string | null;
  rosterSheetNotes?: string | null;
  rosterDayShiftGender?: string | null;
  rosterNightShiftGender?: string | null;
  rosterDayShiftGuardsRequired?: number | null;
  rosterNightShiftGuardsRequired?: number | null;
}

const SUNDAY_HEADER: [number, number, number] = [249, 231, 159];
const SUNDAY_BODY: [number, number, number] = [254, 247, 214];

/**
 * Shift sheet PDF: header band, staff × day matrix (D/N/O), legend and site rules.
 * Landscape A4; Sunday columns highlighted; header rows repeat on continuation pages.
 */
export function generateShiftRosterSheetPDF({
  siteName,
  periodLabel,
  days,
  rows,
  generatedBy,
  rosterSiteRules,
  rosterSheetNotes,
  rosterDayShiftGender,
  rosterNightShiftGender,
  rosterDayShiftGuardsRequired,
  rosterNightShiftGuardsRequired,
}: ShiftRosterSheetPdfInput): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 10;
  let y = 12;

  doc.setFillColor(234, 88, 12);
  doc.rect(0, 0, pageWidth, 1.2, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(0, 0, 0);
  doc.text("SHIFT ROSTER", margin, y);
  doc.text(siteName, pageWidth - margin, y, { align: "right" });
  y += 7;
  doc.setFontSize(10);
  doc.text(periodLabel.toUpperCase(), pageWidth / 2, y, { align: "center" });
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(80, 80, 80);
  doc.text(getGeneratedByText(generatedBy), margin, y);
  y += 6;
  doc.setTextColor(0, 0, 0);

  const n = days.length;
  const fontSize = n <= 14 ? 7.5 : n <= 22 ? 6.5 : n <= 31 ? 5.5 : 5;
  const cellPad = n <= 22 ? 1.5 : 1;

  const head1: string[] = ["G", "Staff"];
  const head2: string[] = ["", ""];
  for (let i = 0; i < n; i++) {
    const day = days[i]!;
    head1.push(format(day, "EEE"));
    head2.push(format(day, "d"));
  }
  head1.push("Contact");
  head2.push("");

  const colCount = 2 + n + 1;
  const body =
    rows.length === 0
      ? [
          [
            {
              content: "No shifts in this period for this site.",
              colSpan: colCount,
              styles: { halign: "center" as const, fontStyle: "normal" as const },
            },
          ],
        ]
      : rows.map((r) => {
          const g = genderPdfLabel(r.gender);
          const name = `${r.firstName} ${r.lastName}`;
          const phone = formatPhoneForDisplay(r.phone) || "—";
          return [g, name, ...r.cells, phone];
        });

  const dayColStart = 2;

  autoTable(doc, {
    startY: y,
    head: [head1, head2],
    body,
    styles: {
      fontSize,
      cellPadding: cellPad,
      ...WIREFRAME_STYLES,
      valign: "middle",
      halign: "center",
    },
    columnStyles: {
      0: { cellWidth: 8, halign: "center" },
      1: { cellWidth: "auto", halign: "left", fontStyle: "normal" },
      [colCount - 1]: { cellWidth: 22, halign: "center", fontSize: fontSize - 0.5 },
    },
    headStyles: {
      ...HEADER_STYLES,
      ...WIREFRAME_STYLES,
      fontSize: fontSize - 0.5,
    },
    alternateRowStyles: {
      fillColor: [252, 252, 252] as [number, number, number],
    },
    margin: { left: margin, right: margin, bottom: 22 },
    tableWidth: pageWidth - 2 * margin,
    showHead: "everyPage",
    didParseCell: (data) => {
      const col = data.column.index;
      if (col >= dayColStart && col < dayColStart + n) {
        const dayIdx = col - dayColStart;
        const day = days[dayIdx];
        if (day && day.getDay() === 0) {
          if (data.section === "head") {
            data.cell.styles.fillColor = SUNDAY_HEADER;
          } else if (data.section === "body") {
            data.cell.styles.fillColor = SUNDAY_BODY;
          }
        }
      }
      if (data.section === "body" && col === 1 && typeof data.row.index === "number" && data.row.index >= 0) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.halign = "left";
      }
    },
  });

  const lastY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
  let footY = lastY + 4;
  if (footY > pageHeight - 26) {
    doc.addPage("a4", "landscape");
    footY = 14;
  }

  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.text(
    "Legend: D Day shift  N Night shift  O Off  M Male  F Female  R Replaced  A AWOL",
    margin,
    footY
  );
  footY += 4;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(180, 40, 40);
  doc.text("Site rules:", margin, footY);
  footY += 3.5;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 40, 40);
  const ruleLines = rosterSiteRulesLines(rosterSiteRules, rosterDayShiftGender, rosterNightShiftGender, {
    rosterDayShiftGuardsRequired,
    rosterNightShiftGuardsRequired,
  });
  const maxTextW = pageWidth - 2 * margin;
  const lineGap = 3.2;
  for (const para of ruleLines) {
    const wrapped = doc.splitTextToSize(para, maxTextW);
    doc.text(wrapped, margin, footY);
    footY += wrapped.length * lineGap;
  }
  const notes = rosterSheetNotes?.trim();
  if (notes) {
    footY += 2;
    if (footY > pageHeight - 20) {
      doc.addPage("a4", "landscape");
      footY = 14;
    }
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("Roster notes:", margin, footY);
    footY += 3.5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    const noteWrapped = doc.splitTextToSize(notes, maxTextW);
    doc.text(noteWrapped, margin, footY);
    footY += noteWrapped.length * lineGap;
  }
  doc.setTextColor(0, 0, 0);

  return doc.output("blob");
}
