"use client";

import Link from "next/link";
import { useState } from "react";
import { Badge, Button, AlertBanner } from "@/components/ui";
import type { ManagedDocument } from "@/lib/msr-api";
import { verifyDocument, rejectDocument } from "@/lib/msr-api";

export interface DocumentDetailsPanelProps {
  document: ManagedDocument;
  token: string;
  onDocumentUpdated: (doc: ManagedDocument) => void;
  canEdit?: boolean;
  canApprove?: boolean;
  onRegenerate?: () => void;
  regenerating?: boolean;
}

export function DocumentDetailsPanel({
  document: doc,
  token,
  onDocumentUpdated,
  canEdit = false,
  canApprove = false,
  onRegenerate,
  regenerating = false,
}: DocumentDetailsPanelProps) {
  const [rejecting, setRejecting] = useState(false);
  const [rejectReason, setRejectReason] = useState("");
  const [actionLoading, setActionLoading] = useState(false);
  const [actionError, setActionError] = useState("");

  const isGenerated = doc.origin === "GENERATED";
  const sourceInfo = doc.sourceInfo;

  const handleVerify = async () => {
    if (!token) return;
    setActionLoading(true);
    setActionError("");
    try {
      const updated = await verifyDocument(token, doc.id);
      onDocumentUpdated(updated);
    } catch (err: any) {
      setActionError(err?.message || "Failed to verify document");
    } finally {
      setActionLoading(false);
    }
  };

  const handleReject = async () => {
    if (!token || !rejectReason.trim()) return;
    setActionLoading(true);
    setActionError("");
    try {
      const updated = await rejectDocument(token, doc.id, rejectReason.trim());
      onDocumentUpdated(updated);
      setRejecting(false);
      setRejectReason("");
    } catch (err: any) {
      setActionError(err?.message || "Failed to reject document");
    } finally {
      setActionLoading(false);
    }
  };

  return (
    <div className="space-y-6 text-sm text-security-navy-800 p-4">
      {actionError && (
        <AlertBanner variant="error" className="mb-4">
          {actionError}
        </AlertBanner>
      )}

      {/* System Generated Document Doctrine Notice */}
      {isGenerated && (
        <div className="rounded-lg border border-amber-200 bg-amber-50/70 p-3.5 space-y-2">
          <div className="flex items-center gap-2">
            <span className="text-amber-800 font-semibold text-xs uppercase tracking-wider">
              System-Generated Document
            </span>
          </div>
          <p className="text-xs text-amber-900 leading-relaxed">
            This document represents live Plethora ERP records. Direct text alteration is disabled to ensure data integrity.
          </p>
          <div className="flex flex-wrap items-center gap-2 pt-1">
            {sourceInfo?.editSourceUrl && (
              <Link
                href={sourceInfo.editSourceUrl}
                className="btn-primary text-xs py-1 px-3 inline-flex items-center gap-1.5"
              >
                <span>Edit Source Data</span>
                <span>↗</span>
              </Link>
            )}
            {canEdit && onRegenerate && (
              <Button
                variant="secondary"
                size="sm"
                onClick={onRegenerate}
                loading={regenerating}
                className="text-xs"
              >
                Regenerate PDF
              </Button>
            )}
          </div>
        </div>
      )}

      {/* Origin & Source Info */}
      <div>
        <h3 className="text-xs font-bold uppercase tracking-wider text-security-navy-500 mb-2">
          Source Information
        </h3>
        <div className="card-dashboard p-3 space-y-2 text-xs">
          <div className="flex justify-between items-center">
            <span className="text-security-navy-500">Origin:</span>
            <Badge variant={isGenerated ? "warning" : "neutral"}>
              {isGenerated ? "Generated by Plethora" : "Uploaded Attachment"}
            </Badge>
          </div>
          {doc.sourceModule && (
            <div className="flex justify-between items-center">
              <span className="text-security-navy-500">Source Module:</span>
              <span className="font-semibold text-security-navy-800">{doc.sourceModule}</span>
            </div>
          )}
          {sourceInfo && (
            <div className="flex justify-between items-center">
              <span className="text-security-navy-500">Origin Description:</span>
              <span className="font-medium text-security-navy-900">{sourceInfo.sourceLabel}</span>
            </div>
          )}
        </div>
      </div>

      {/* Linked Entity */}
      {(doc.employee || doc.client || doc.site || doc.clientContract) && (
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-security-navy-500 mb-2">
            Linked Entity
          </h3>
          <div className="card-dashboard p-3 space-y-2 text-xs">
            {doc.employee && (
              <div className="flex justify-between items-center">
                <span className="text-security-navy-500">Employee:</span>
                <Link
                  href={`/employees?search=${encodeURIComponent(doc.employee.employeeNumber || doc.employee.lastName)}`}
                  className="font-semibold text-security-navy-900 hover:text-security-navy-700 underline"
                >
                  {doc.employee.firstName} {doc.employee.lastName}
                  {doc.employee.employeeNumber ? ` (${doc.employee.employeeNumber})` : ""}
                </Link>
              </div>
            )}
            {doc.client && (
              <div className="flex justify-between items-center">
                <span className="text-security-navy-500">Client:</span>
                <Link
                  href={`/clients?search=${encodeURIComponent(doc.client.name)}`}
                  className="font-semibold text-security-navy-900 hover:text-security-navy-700 underline"
                >
                  {doc.client.name}
                </Link>
              </div>
            )}
            {doc.site && (
              <div className="flex justify-between items-center">
                <span className="text-security-navy-500">Site:</span>
                <Link
                  href={`/sites?search=${encodeURIComponent(doc.site.name)}`}
                  className="font-semibold text-security-navy-900 hover:text-security-navy-700 underline"
                >
                  {doc.site.name}
                </Link>
              </div>
            )}
            {doc.clientContract && (
              <div className="flex justify-between items-center">
                <span className="text-security-navy-500">Contract:</span>
                <span className="font-semibold text-security-navy-800">
                  {doc.clientContract.contractNumber} - {doc.clientContract.title}
                </span>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Verification & Compliance */}
      <div>
        <h3 className="text-xs font-bold uppercase tracking-wider text-security-navy-500 mb-2">
          Verification & Lifecycle
        </h3>
        <div className="card-dashboard p-3 space-y-3 text-xs">
          <div className="flex justify-between items-center">
            <span className="text-security-navy-500">Verification Status:</span>
            <Badge
              variant={
                doc.verificationStatus === "VERIFIED"
                  ? "success"
                  : doc.verificationStatus === "REJECTED"
                  ? "error"
                  : "warning"
              }
            >
              {doc.verificationStatus ? doc.verificationStatus.replace(/_/g, " ") : "PENDING"}
            </Badge>
          </div>

          {doc.verifiedBy && (
            <div className="flex justify-between items-center">
              <span className="text-security-navy-500">Verified By:</span>
              <span className="text-security-navy-800">{doc.verifiedBy.name}</span>
            </div>
          )}

          {doc.verifiedAt && (
            <div className="flex justify-between items-center">
              <span className="text-security-navy-500">Verified Date:</span>
              <span className="text-security-navy-800">
                {new Date(doc.verifiedAt).toLocaleDateString()}
              </span>
            </div>
          )}

          {doc.rejectionReason && (
            <div className="p-2 bg-red-50 border border-red-200 rounded text-red-800">
              <p className="font-semibold mb-0.5">Rejection Note:</p>
              <p>{doc.rejectionReason}</p>
            </div>
          )}

          {/* Verification actions */}
          {canApprove && doc.verificationStatus !== "VERIFIED" && !rejecting && (
            <div className="flex items-center gap-2 pt-2 border-t border-security-navy-100">
              <Button
                variant="primary"
                size="sm"
                className="w-full"
                onClick={handleVerify}
                loading={actionLoading}
              >
                Verify Document
              </Button>
              <Button
                variant="destructive"
                size="sm"
                className="w-full"
                onClick={() => setRejecting(true)}
                disabled={actionLoading}
              >
                Reject
              </Button>
            </div>
          )}

          {rejecting && (
            <div className="pt-2 border-t border-security-navy-100 space-y-2">
              <label htmlFor="rejection-reason" className="block font-semibold text-security-navy-700">
                Reason for Rejection:
              </label>
              <textarea
                id="rejection-reason"
                value={rejectReason}
                onChange={(e) => setRejectReason(e.target.value)}
                placeholder="e.g. Incomplete scan, missing stamp, blurred registration number…"
                className="input-modern w-full text-xs p-2"
                rows={2}
              />
              <div className="flex items-center gap-2">
                <Button
                  variant="destructive"
                  size="sm"
                  onClick={handleReject}
                  loading={actionLoading}
                  disabled={!rejectReason.trim()}
                >
                  Confirm Rejection
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setRejecting(false)}
                >
                  Cancel
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Document Properties */}
      <div>
        <h3 className="text-xs font-bold uppercase tracking-wider text-security-navy-500 mb-2">
          Document Details
        </h3>
        <div className="card-dashboard p-3 space-y-2 text-xs">
          {doc.documentNumber && (
            <div className="flex justify-between items-center">
              <span className="text-security-navy-500">Document No:</span>
              <span className="font-mono text-security-navy-900">{doc.documentNumber}</span>
            </div>
          )}
          {doc.issuingAuthority && (
            <div className="flex justify-between items-center">
              <span className="text-security-navy-500">Issuing Authority:</span>
              <span className="text-security-navy-800">{doc.issuingAuthority}</span>
            </div>
          )}
          <div className="flex justify-between items-center">
            <span className="text-security-navy-500">Issue Date:</span>
            <span className="text-security-navy-800">
              {doc.issueDate ? new Date(doc.issueDate).toLocaleDateString() : "Not specified"}
            </span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-security-navy-500">Expiry Date:</span>
            <span className="text-security-navy-800">
              {doc.doesNotExpire
                ? "Does not expire"
                : doc.expiryDate
                ? new Date(doc.expiryDate).toLocaleDateString()
                : "Not specified"}
            </span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-security-navy-500">Sensitivity:</span>
            <span className={doc.isSensitive ? "text-amber-700 font-semibold" : "text-security-navy-600"}>
              {doc.isSensitive ? "Confidential / Restricted" : "Standard"}
            </span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-security-navy-500">Uploaded By:</span>
            <span className="text-security-navy-800">{doc.uploadedBy?.name || "System"}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-security-navy-500">Created:</span>
            <span className="text-security-navy-800">{new Date(doc.createdAt).toLocaleDateString()}</span>
          </div>
        </div>
      </div>

      {/* Notes */}
      {doc.notes && (
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-security-navy-500 mb-2">
            Notes
          </h3>
          <div className="card-dashboard p-3 text-xs text-security-navy-700 whitespace-pre-wrap">
            {doc.notes}
          </div>
        </div>
      )}
    </div>
  );
}
