-- AlterTable
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "rosterDayShiftStartTime" TEXT DEFAULT '06:00';
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "rosterDayShiftEndTime" TEXT DEFAULT '18:00';
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "rosterNightShiftStartTime" TEXT DEFAULT '18:00';
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "rosterNightShiftEndTime" TEXT DEFAULT '06:00';
